### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ElDavoo** [txthinking/testsocks5#1]
# testsocks5 -s 127.0.0.1:40000
Info:    Testing TCP
Error:   TypeError: Error parsing args: data did not match any variant of untagged enum ArgsEnum
    at Object.opAsync (deno:core/01_core.js:154:35)
    at opConnect (deno:ext/net/01_net.js:45:17)
    at Object.connect (deno:ext/net/01_net.js:325:23)
    at Object.connect (deno:ext/net/04_net_unstable.js:40:18)
    at https://raw.githubusercontent.com/txthinking/testsocks5/master/testsocks5.js:26:24

**Comment by txthinking** [comment]
How about the latest version?
```
nami install testsocks5
```

**Comment by txthinking** [comment]
try v20220407
